language: csharp
solution: SigmaValidation.sln
install:
    - nuget restore SigmaValidation.sln
    - nuget install xunit.runners -Version 2.4.0 -OutputDirectory testrunner
script:
    - msbuild /p:Configuration=Release SigmaValidation.sln